// AUTO-GENERATED by scripts/exportBoardLayout.mjs
import type { MapGraph } from '../core/types';

export const map: MapGraph = {
  "nodes": {
    "hangzhou": {
      "id": "hangzhou",
      "x": 819,
      "y": 567,
      "label": "Lin'an",
      "kind": "city"
    },
    "kaifeng": {
      "id": "kaifeng",
      "x": 609,
      "y": 276,
      "label": "Bianjing",
      "kind": "city"
    },
    "nanjing": {
      "id": "nanjing",
      "x": 738,
      "y": 454,
      "label": "Jiankang",
      "kind": "city"
    },
    "suzhou-js": {
      "id": "suzhou-js",
      "x": 820,
      "y": 480,
      "label": "Suzhou",
      "kind": "city"
    },
    "zhenjiang": {
      "id": "zhenjiang",
      "x": 808,
      "y": 405,
      "label": "Zhenjiang",
      "kind": "city"
    },
    "yangzhou": {
      "id": "yangzhou",
      "x": 787,
      "y": 317,
      "label": "Yangzhou",
      "kind": "city"
    },
    "huaiyin": {
      "id": "huaiyin",
      "x": 701,
      "y": 295,
      "label": "Chuzhou",
      "kind": "city"
    },
    "huaiyang": {
      "id": "huaiyang",
      "x": 642,
      "y": 335,
      "label": "Huaiyang",
      "kind": "city"
    },
    "hefei": {
      "id": "hefei",
      "x": 706,
      "y": 378,
      "label": "Luzhou",
      "kind": "city"
    },
    "ningbo": {
      "id": "ningbo",
      "x": 910,
      "y": 694,
      "label": "Mingzhou",
      "kind": "city"
    },
    "nanchang": {
      "id": "nanchang",
      "x": 732,
      "y": 609,
      "label": "Nanchang",
      "kind": "city"
    },
    "jiujiang": {
      "id": "jiujiang",
      "x": 673,
      "y": 534,
      "label": "Jiujiang",
      "kind": "city"
    },
    "jianzhou-fj": {
      "id": "jianzhou-fj",
      "x": 772,
      "y": 683,
      "label": "Jianzhou",
      "kind": "city"
    },
    "yanjing": {
      "id": "yanjing",
      "x": 574,
      "y": 122,
      "label": "Yanjing",
      "kind": "city"
    },
    "daming": {
      "id": "daming",
      "x": 565,
      "y": 203,
      "label": "Daming",
      "kind": "city"
    },
    "taiyuan": {
      "id": "taiyuan",
      "x": 476,
      "y": 228,
      "label": "Taiyuan",
      "kind": "city"
    },
    "cangzhou": {
      "id": "cangzhou",
      "x": 641,
      "y": 161,
      "label": "Cangzhou",
      "kind": "city"
    },
    "taizhou": {
      "id": "taizhou",
      "x": 800,
      "y": 232,
      "label": "Taizhou",
      "kind": "city"
    },
    "haizhou": {
      "id": "haizhou",
      "x": 717,
      "y": 209,
      "label": "Haizhou",
      "kind": "city"
    },
    "xuanzhou": {
      "id": "xuanzhou",
      "x": 720,
      "y": 505,
      "label": "Xuanzhou",
      "kind": "city"
    },
    "fuzhou": {
      "id": "fuzhou",
      "x": 834,
      "y": 736,
      "label": "Fuzhou",
      "kind": "city"
    },
    "quanzhou": {
      "id": "quanzhou",
      "x": 760,
      "y": 760,
      "label": "Quanzhou",
      "kind": "city"
    },
    "tanzhou": {
      "id": "tanzhou",
      "x": 659,
      "y": 606,
      "label": "Tanzhou",
      "kind": "city"
    },
    "zhaozhou": {
      "id": "zhaozhou",
      "x": 502,
      "y": 158,
      "label": "Zhaozhou",
      "kind": "city"
    },
    "chengdu": {
      "id": "chengdu",
      "x": 290,
      "y": 456,
      "label": "Chengdu",
      "kind": "city"
    },
    "xingyuan": {
      "id": "xingyuan",
      "x": 445,
      "y": 401,
      "label": "Xingyuan",
      "kind": "city"
    },
    "lizhou": {
      "id": "lizhou",
      "x": 367,
      "y": 434,
      "label": "Lizhou",
      "kind": "city"
    },
    "shangjing": {
      "id": "shangjing",
      "x": 568,
      "y": 40,
      "label": "Shangjing",
      "kind": "city"
    },
    "yueyang": {
      "id": "yueyang",
      "x": 599,
      "y": 568,
      "label": "Yueyang",
      "kind": "city"
    },
    "xiangyang": {
      "id": "xiangyang",
      "x": 529,
      "y": 435,
      "label": "Xiangyang",
      "kind": "city"
    },
    "shaoxing": {
      "id": "shaoxing",
      "x": 897,
      "y": 608,
      "label": "Shaoxing",
      "kind": "city"
    },
    "guangzhou": {
      "id": "guangzhou",
      "x": 704,
      "y": 697,
      "label": "Guangzhou",
      "kind": "city"
    },
    "yingchang": {
      "id": "yingchang",
      "x": 567,
      "y": 354,
      "label": "Yingchang",
      "kind": "city"
    },
    "ezhou": {
      "id": "ezhou",
      "x": 585,
      "y": 504,
      "label": "Ezhou",
      "kind": "city"
    },
    "yanan": {
      "id": "yanan",
      "x": 432,
      "y": 307,
      "label": "Yanan",
      "kind": "city"
    }
  },
  "edges": {
    "e1": {
      "id": "e1",
      "a": "yangzhou",
      "b": "zhenjiang",
      "kinds": [
        "river"
      ]
    },
    "e2": {
      "id": "e2",
      "a": "nanjing",
      "b": "zhenjiang",
      "kinds": [
        "river",
        "road"
      ]
    },
    "e3": {
      "id": "e3",
      "a": "huaiyin",
      "b": "yangzhou",
      "kinds": [
        "river",
        "road"
      ]
    },
    "e4": {
      "id": "e4",
      "a": "huaiyang",
      "b": "huaiyin",
      "kinds": [
        "river",
        "road"
      ]
    },
    "e5": {
      "id": "e5",
      "a": "huaiyin",
      "b": "kaifeng",
      "kinds": [
        "canal"
      ]
    },
    "e6": {
      "id": "e6",
      "a": "hefei",
      "b": "huaiyang",
      "kinds": [
        "path"
      ]
    },
    "e7": {
      "id": "e7",
      "a": "jiujiang",
      "b": "nanchang",
      "kinds": [
        "river",
        "path"
      ]
    },
    "e8": {
      "id": "e8",
      "a": "hangzhou",
      "b": "nanchang",
      "kinds": [
        "path"
      ]
    },
    "e9": {
      "id": "e9",
      "a": "jianzhou-fj",
      "b": "nanchang",
      "kinds": [
        "path"
      ]
    },
    "e10": {
      "id": "e10",
      "a": "huaiyang",
      "b": "kaifeng",
      "kinds": [
        "river",
        "road"
      ]
    },
    "e11": {
      "id": "e11",
      "a": "daming",
      "b": "kaifeng",
      "kinds": [
        "road",
        "canal"
      ]
    },
    "e12": {
      "id": "e12",
      "a": "daming",
      "b": "yanjing",
      "kinds": [
        "road"
      ]
    },
    "e13": {
      "id": "e13",
      "a": "cangzhou",
      "b": "yanjing",
      "kinds": [
        "road",
        "canal"
      ]
    },
    "e14": {
      "id": "e14",
      "a": "cangzhou",
      "b": "daming",
      "kinds": [
        "road",
        "canal"
      ]
    },
    "e15": {
      "id": "e15",
      "a": "daming",
      "b": "zhaozhou",
      "kinds": [
        "road"
      ]
    },
    "e16": {
      "id": "e16",
      "a": "taizhou",
      "b": "yangzhou",
      "kinds": [
        "river"
      ]
    },
    "e17": {
      "id": "e17",
      "a": "haizhou",
      "b": "huaiyin",
      "kinds": [
        "river",
        "road"
      ]
    },
    "e18": {
      "id": "e18",
      "a": "haizhou",
      "b": "taizhou",
      "kinds": [
        "river"
      ]
    },
    "e19": {
      "id": "e19",
      "a": "nanjing",
      "b": "xuanzhou",
      "kinds": [
        "path",
        "river"
      ]
    },
    "e20": {
      "id": "e20",
      "a": "jiujiang",
      "b": "xuanzhou",
      "kinds": [
        "path"
      ]
    },
    "e21": {
      "id": "e21",
      "a": "hangzhou",
      "b": "shaoxing",
      "kinds": [
        "path",
        "canal"
      ]
    },
    "e22": {
      "id": "e22",
      "a": "fuzhou",
      "b": "jianzhou-fj",
      "kinds": [
        "path"
      ]
    },
    "e23": {
      "id": "e23",
      "a": "fuzhou",
      "b": "quanzhou",
      "kinds": [
        "path",
        "coast"
      ]
    },
    "e24": {
      "id": "e24",
      "a": "jianzhou-fj",
      "b": "quanzhou",
      "kinds": [
        "path"
      ]
    },
    "e25": {
      "id": "e25",
      "a": "nanchang",
      "b": "tanzhou",
      "kinds": [
        "path"
      ]
    },
    "e26": {
      "id": "e26",
      "a": "jiujiang",
      "b": "tanzhou",
      "kinds": [
        "path"
      ]
    },
    "e27": {
      "id": "e27",
      "a": "daming",
      "b": "taiyuan",
      "kinds": [
        "path"
      ]
    },
    "e28": {
      "id": "e28",
      "a": "fuzhou",
      "b": "ningbo",
      "kinds": [
        "coast"
      ]
    },
    "e29": {
      "id": "e29",
      "a": "xingyuan",
      "b": "yanan",
      "kinds": [
        "path"
      ]
    },
    "e30": {
      "id": "e30",
      "a": "lizhou",
      "b": "xingyuan",
      "kinds": [
        "path"
      ]
    },
    "e31": {
      "id": "e31",
      "a": "chengdu",
      "b": "lizhou",
      "kinds": [
        "path"
      ]
    },
    "e32": {
      "id": "e32",
      "a": "tanzhou",
      "b": "yueyang",
      "kinds": [
        "river",
        "path"
      ]
    },
    "e33": {
      "id": "e33",
      "a": "jiujiang",
      "b": "yueyang",
      "kinds": [
        "river"
      ]
    },
    "e34": {
      "id": "e34",
      "a": "ezhou",
      "b": "yueyang",
      "kinds": [
        "road",
        "river"
      ]
    },
    "e35": {
      "id": "e35",
      "a": "ezhou",
      "b": "jiujiang",
      "kinds": [
        "river"
      ]
    },
    "e36": {
      "id": "e36",
      "a": "ezhou",
      "b": "xiangyang",
      "kinds": [
        "road",
        "river"
      ]
    },
    "e37": {
      "id": "e37",
      "a": "xiangyang",
      "b": "yingchang",
      "kinds": [
        "road"
      ]
    },
    "e38": {
      "id": "e38",
      "a": "ningbo",
      "b": "shaoxing",
      "kinds": [
        "path",
        "canal"
      ]
    },
    "e39": {
      "id": "e39",
      "a": "kaifeng",
      "b": "yingchang",
      "kinds": [
        "road"
      ]
    },
    "e40": {
      "id": "e40",
      "a": "huaiyang",
      "b": "yingchang",
      "kinds": [
        "road"
      ]
    },
    "e41": {
      "id": "e41",
      "a": "shangjing",
      "b": "yanjing",
      "kinds": [
        "path"
      ]
    },
    "e42": {
      "id": "e42",
      "a": "taiyuan",
      "b": "yanan",
      "kinds": [
        "path"
      ]
    },
    "e43": {
      "id": "e43",
      "a": "xiangyang",
      "b": "xingyuan",
      "kinds": [
        "path"
      ]
    },
    "e44": {
      "id": "e44",
      "a": "guangzhou",
      "b": "quanzhou",
      "kinds": [
        "coast"
      ]
    },
    "e45": {
      "id": "e45",
      "a": "guangzhou",
      "b": "nanchang",
      "kinds": [
        "path"
      ]
    },
    "e46": {
      "id": "e46",
      "a": "cangzhou",
      "b": "haizhou",
      "kinds": [
        "road"
      ]
    },
    "e47": {
      "id": "e47",
      "a": "taiyuan",
      "b": "zhaozhou",
      "kinds": [
        "path"
      ]
    },
    "e48": {
      "id": "e48",
      "a": "yanjing",
      "b": "zhaozhou",
      "kinds": [
        "road"
      ]
    },
    "e49": {
      "id": "e49",
      "a": "suzhou-js",
      "b": "zhenjiang",
      "kinds": [
        "canal",
        "road"
      ]
    },
    "e50": {
      "id": "e50",
      "a": "hangzhou",
      "b": "suzhou-js",
      "kinds": [
        "canal"
      ]
    },
    "e51": {
      "id": "e51",
      "a": "jiujiang",
      "b": "nanjing",
      "kinds": [
        "river"
      ]
    },
    "e52": {
      "id": "e52",
      "a": "nanjing",
      "b": "suzhou-js",
      "kinds": [
        "road"
      ]
    },
    "e53": {
      "id": "e53",
      "a": "hefei",
      "b": "huaiyin",
      "kinds": [
        "path"
      ]
    },
    "e54": {
      "id": "e54",
      "a": "hefei",
      "b": "nanjing",
      "kinds": [
        "river"
      ]
    }
  }
} as const;
